spring.application.name=backend

# --- Database PostgreSQL en Render (externa) ---
spring.datasource.url=jdbc:postgresql://dpg-d4g8giu3jp1c73dfvjrg-a.oregon-postgres.render.com:5432/bdpopshoes?sslmode=require
spring.datasource.username=bdpopshoes_user
spring.datasource.password=1Jh2ydbaQBdcESLxvI3sHdbuNrOFeeOM
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# --- helath ---
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
# --- Hikari ---
spring.datasource.hikari.data-source-properties.sslmode=require

# --- Swagger ---
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# --- Server ---
server.address=0.0.0.0
server.port=${PORT:8080}

# --- Jackson ---
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970